require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'lib/generators/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

# Rails specific
Rails/ApplicationRecord:
  Exclude:
    - 'spec/dummy/**/*'

Rails/SkipsModelValidations:
  Enabled: false

# RSpec specific
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 3