name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Configure gem credentials
      run: |
        mkdir -p ~/.gem
        cat > ~/.gem/credentials << EOF
        ---
        :rubygems_api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        EOF
        chmod 0600 ~/.gem/credentials

    - name: Run tests
      run: |
        bundle exec rspec
        bundle exec rubocop

    - name: Generate documentation
      run: bundle exec rake yard

    - name: Build gem
      run: bundle exec rake build

    - name: Publish to RubyGems
      run: bundle exec rake release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: pkg/*.gem
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref_name, 'pre') || contains(github.ref_name, 'rc') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

