name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']
        rails-version: ['6.1', '7.0', '7.1']
        exclude:
          - ruby-version: '3.0'
            rails-version: '7.1'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Install Rails ${{ matrix.rails-version }}
      run: |
        gem install rails -v "~> ${{ matrix.rails-version }}.0"
        bundle update rails
    
    - name: Create coverage directory
      run: mkdir -p coverage
    
    - name: Run RSpec tests
      run: |
        bundle exec rspec --format documentation
      env:
        COVERAGE: true
        RAILS_ENV: test
    
    - name: Upload coverage to Codecov
      if: matrix.ruby-version == '3.2' && matrix.rails-version == '7.1'
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage/coverage.xml,./coverage/.resultset.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Run RuboCop
      run: bundle exec rubocop --format github

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Run security audit
      run: |
        gem install bundler-audit
        bundle audit check --update || true

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Build gem
      run: bundle exec gem build attio-rails.gemspec
    
    - name: Check gem installation
      run: |
        gem_file=$(ls attio-rails-*.gem | head -1)
        gem install "$gem_file" --development
        ruby -e "require 'attio/rails'; puts 'Gem loads successfully'"
    
    - name: Upload gem artifact
      uses: actions/upload-artifact@v4
      with:
        name: gem-build
        path: attio-rails-*.gem